const host = "http://127.0.0.1:3001"

export const getMagicLinkUrl: string = `${host}/create-magic-link`
export const authRequestUrl: string = `${host}/authorise`
export const getLoggedInUserWishesUrl: string = `${host}/getAllWishes`
export const addNewWishUrl: string = `${host}/addNewWish`
export const deleteWishUrl: string = `${host}/deleteWish`
export const editWishUrl: string = `${host}/modifyWish`
export const setUsernameUrl: string = `${host}/setUsername`
export const getUsernameUrl: string = `${host}/getUsername`
export const getPublicWishesUrl: string = `${host}/getPublicWishes/`
export const getAllRoomsUrl: string = `${host}/getAllRooms`
export const createNewRoomUrl: string = `${host}/createRoom`
export const getWishesByUserIdUrl: string = `${host}/getWishesById/`
export const getUsernameByUserIdUrl: string = `${host}/getUsernameByUserId/`
export const addNewUserUrl: string = `${host}/addUserToRoom`
export const addUserViaLinkUrl: string = `${host}/addUserViaLink`
export const linkForEddingUser: string = "http://127.0.0.1:3000/adduser/"
export const userLink: string = "http://127.0.0.1:3000/user/"